baseURL: https://www.y15a.com/
title: y15a
theme: PaperMod
defaultContentLanguage: "ja"
languages:
  ja:
    languageCode: ja-JP
    languageName: 日本語
    params:
      homeInfoParams:
        Title: Howdy, I'm Yoshi.
        Content: 柿原祥之。起業家、ソフトウェア技術者。100+自治体へAIによる英語教育支援をするジョイズ株式会社の創業CEO。
    menu:
      main:
        - name: タグ 
          url: tags
          weight: 1
        - name: アーカイブ
          url: archives
          weight: 5
    taxonomies:
      tag: Tags
  en:
    languageCode: en-GB
    languageName: English
    params:
      homeInfoParams:
        Title: Howdy, I'm Yoshi.
        Content: Yoshiyuki Kakihara. Entrepreneur, Software Engineer. Father of two.
    menu:
      main:
        - name: Tags
          url: tags
          weight: 1
        - name: Archive
          url: archives
          weight: 5
    taxonomies:
      tag: Tags

params:
  socialIcons:
    - name: "github"
      url: "https://github.com/y15a"
    - name: "facebook"
      url: "https://facebook.com/yoshiyuki.kakihara/"
    - name: "twitter"
      url: "https://x.com/y15a_/"
    - name: "mastodon"
      url: "https://mas.to/@y15a"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/yoshiyuki-kakihara-6a158322/"

services:
  googleAnalytics:
    id: G-4NYFPSJF0F

